### PR TITLE
Apply PSR-1 & PSR-2 via php-cs-fixer.

### PR DESCRIPTION
**Pull request by stephpy**

### CODE REVIEW

**Comment by shouze** [comment]
:+1: ping @Hywan

**Comment by Hywan** [comment]
Ok, I think we have enough questions for this first draft ;-).

**Comment by jubianchi** [comment]
My 2 cents: the fastest way to adopt PSR-* is to just adopt it using existing tools in their actual state. Adding customizations here and there (add newline after braces, aligns things in some cases but not in others, ...) will lead to inconsistent code style and won't help contributors and reviewers. 

Using cs-fixer as-is has the pros. of providing a consistent and predictable result. The contribuot will only have to fire up cs-fixer, wait for it to do the job and that's it. Reviewers will see in a matter of seconds if cs-fixer has been run. 

Moreover, the contributing sections will be simple:

> befire send any PR please run your code through `php-cs-fixer`...

Addîg custom rules above PSRs will not change anything: in the end, CSes will still be custom, will have to be documented and ideally tools will have to be written to support those custom rules. This means more work to do before anything can be migrated and then more tool to maintain, support, release and document.

**Comment by Hywan** [comment]
I say it one more time: The goal of this PR is to check if we can apply PSR-1 and 2 on Hoa's code, and, because PSR-1 and 2 are not exhaustive, what are our degree of freedom.

So far, what we would like to custom (because it's not defined in PSR-1 and 2) is:
  * no trailing comma in array (`[1, 2]` is ok, `[1, 2,]` is nok),
  * vertical alignment can be compatible with PSR-1 and 2 if done manually with left-aligned operands, like this:
```php
if ($x   === $y ||
    $abc === $def) {
```
  * one blank line before `namespace`,
  * one blank line after `{`,
  * remove `@access`.

Extra point we have to discuss is:
  * adding spaces around `.` (concatenation operator).

Everything else is PSR-1 and 2 and we agree with that. The only point that is **not** PSR-1 and 2 is the “extra point” above. I would love to have spaces around `.`. Is it a huge violation or something we can deal with? If it is too much “trolly”, we can vote.

**Comment by Hywan** [comment]
I also propose to write the coding styles, by saying it is PSR-1 and 2 compatible, but because they are not exhaustive, we refined them by adding few more rules like… and… and… etc. In addition to the point I was mentionning in the previous comment, we have to specify how “blocks of instructions” are defined. For instance:
```php
$a = 1;
$b = 2;

foreach (…) {
```
is ok, while:
```php
$a = 1;
$b = 2;
foreach (…) {
```
is nok.

By using PSR-1 and 2, the coding style will be short and quick to write.

Moreover, like @Metalaka suggested, we can use `Hoa\Devtools` to store the `php-cs-fixer` configuration file.

Thoughts?

**Comment by jubianchi** [comment]
@Hywan to make cs-fixer exhaustive with your rules, you will have to write a good configuration file but also some custom fixers which is not always easy.

It seems OK to me if everything is documented and tooled. If contributors and/or reviewers have to do anything manually, I think it will make less sense to change CS.

> saying it is PSR-1 and 2 compatible, but because they are not exhaustive

Unfortunately, there is **no exhaustive** CS ruleset. You will always have holes. How do you indent closures, and closures in closures ? (for example) How do you layout chained elvis-operators ? ... 

I can think of about a hundred question like the previous ones.

**Comment by Hywan** [comment]
@jubianchi Yup, they are not going to be exhaustive, but we use PSR-1 and 2 as a basis, and then add more rules in our CS documentation. If `php-cs-fixer` is not powerful enough to handle all of them, either we patch php-cs-fixer (a contribution to the PHP community) or we do the fix manually (after the run of php-cs-fixer), it's not going to be a big deal because they are edge cases.

Does somone know how to define in php-cs-fixer custom points I mentionned in https://github.com/hoaproject/Websocket/pull/25#issuecomment-72615641?

**Comment by jubianchi** [comment]
@Hywan only thing I found in the README:

> A fixer is a class that tries to fix one CS issue (a Fixer class must implement FixerInterface).
>
> https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#fixers

**Comment by Hywan** [comment]
@jubianchi Let's start with a configuration file. We will see after.

@stephpy What do you think of the recent comments?

**Comment by stephpy** [comment]
I'm agree with @jubianchi, i think it's better to follow `php-cs-fixer` without modifying anything. 

But if we have custom fixer integrated to `php-cs-fixer` ... why not. I will not say i'm favorable because i don't like new CS you mentioned (spaces between dot, etc...). But why not, i'm not closed to it.

**Comment by Hywan** [comment]
@stephpy There is a lot of `[symfony]` and `[contrib]` rules, so why not adding ours :-)?

So, could you try to re-run php-cs-fixer with the first points mentionend in https://github.com/hoaproject/Websocket/pull/25#issuecomment-72615641?

**Comment by stephpy** [comment]
I did only one manual thing, I setted in one line a class definition (i said it in comment).
php-cs-fixer did the rest, so i have to do it manually and we'll have to do it manually on each libraries.

**Comment by stephpy** [comment]
We should decide before ...
What we keep from php-cs-fixer, what we add in hoa specific cs ...

**Comment by Hywan** [comment]
@stephpy The current patch is good, except this few points: https://github.com/hoaproject/Websocket/pull/25#issuecomment-72615641. Could we apply these points with php-cs-fixer's options?

**Comment by stephpy** [comment]
Don't know:

- trailing comma: i guess yes
- vertical align: looks complicated
- one blank line before namespace: i guess yes
- one blank line after {: looks complicated
- remove `@access`: i guess yes
- spaces around `.`: i don't know.

**Comment by Hywan** [comment]
I sum up:
  * trailing comma (it's already the case, we just need to not touch it),
  * one blank line before namespace (it's already the case, we just need to not touch it),
  * one blank line after `{` (it's already the case, we just need to not touch it),
  * remove `@access`,
  * spaces around `.` (it's already the case, we just need to not touch it).

**Comment by Hywan** [comment]
@stephpy Do you know how to use php-cs-fixer to do https://github.com/hoaproject/Central/issues/13 in the same time?

**Comment by stephpy** [comment]
Nope, never used php-cs-fixer to write a filter.

**Comment by camael24** [comment]
I write something on github for sohoa/framework you can take a look :-] i don't know if it can help 

Envoyé de mon iPad

**Comment by Hywan** [comment]
@camael24 Any link?

**Comment by camael24** [comment]
https://github.com/sohoa/framework/blob/master/.php_cs not sure if it can help :dancer:

**Comment by Hywan** [comment]
To sum up (after https://github.com/hoaproject/Websocket/pull/25#issuecomment-72818895):
  * trailing comma: **not PSR-2**,
  * one blank line before namespace: **PSR-2**,
  * one blank line after `{`: **unspecified** but I am going to define a rule for that,
  * remove `@access`: **done**,
  * spaces around `.`: **not PSR-2**.

When we run `php-cs-fixer` without any options, it applies PSR-0, -2 and Symfony fixers, and I don't want Symfony fixers :-). So almost all problems are solved. Only the “block rule” must be defined, a big part… See https://github.com/hoaproject/Devtools/pull/11 for the rest!

**Pull request closed without merging**
