### PR TITLE
Handshake EnableEncryption

### PR DESCRIPTION
**Pull request by Pierozi**
Set encryption if TLS mode enable.

Address to #77

### CODE REVIEW

**Comment by shulard** [comment]
Hello,

Is it possible that the connection encryption had been enable before the `doHandshake` call ?

Because if it's true, we must check that encryption is not already enabled before enabling with `ENCRYPTION_TLS`.

**Comment by Hywan** [comment]
@shulard Correct! Good point.
@Pierozi Please, add a test to ensure the connection is not already encrypted (with `Hoa\Socket\Connection\Connection::isEncrypted` I guess).

**Comment by Pierozi** [comment]
Yup good catch @shulard, heven if handshake must be the first

**Comment by Hywan** [comment]
@Pierozi What's the next step?

**Pull request merged**
